//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulacrumAdditions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimulacrumAdditions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ArtifactOff {
            get {
                object obj = ResourceManager.GetObject("ArtifactOff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ArtifactOn {
            get {
                object obj = ResourceManager.GetObject("ArtifactOn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GiantGupBody {
            get {
                object obj = ResourceManager.GetObject("GiantGupBody", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HanD_Diffuse {
            get {
                object obj = ResourceManager.GetObject("HanD_Diffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HanD_Emission {
            get {
                object obj = ResourceManager.GetObject("HanD_Emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HanDWeapon_Diffuse {
            get {
                object obj = ResourceManager.GetObject("HanDWeapon_Diffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PinktexCaptainJacketDiffuseW {
            get {
                object obj = ResourceManager.GetObject("PinktexCaptainJacketDiffuseW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PinktexCaptainPaletteW {
            get {
                object obj = ResourceManager.GetObject("PinktexCaptainPaletteW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PinktexCaptainPaletteW2 {
            get {
                object obj = ResourceManager.GetObject("PinktexCaptainPaletteW2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PinktexCaptainPaletteW3 {
            get {
                object obj = ResourceManager.GetObject("PinktexCaptainPaletteW3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RoRRHANDTex {
            get {
                object obj = ResourceManager.GetObject("RoRRHANDTex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RoRRHANDTexEmission {
            get {
                object obj = ResourceManager.GetObject("RoRRHANDTexEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinChefIcon {
            get {
                object obj = ResourceManager.GetObject("skinChefIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinChefIconRed {
            get {
                object obj = ResourceManager.GetObject("skinChefIconRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconCaptainRED {
            get {
                object obj = ResourceManager.GetObject("skinIconCaptainRED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconCommando {
            get {
                object obj = ResourceManager.GetObject("skinIconCommando", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconCommandoSOTV {
            get {
                object obj = ResourceManager.GetObject("skinIconCommandoSOTV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconCroco {
            get {
                object obj = ResourceManager.GetObject("skinIconCroco", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconHuntress {
            get {
                object obj = ResourceManager.GetObject("skinIconHuntress", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconLoader {
            get {
                object obj = ResourceManager.GetObject("skinIconLoader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconMage {
            get {
                object obj = ResourceManager.GetObject("skinIconMage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconMageOrange {
            get {
                object obj = ResourceManager.GetObject("skinIconMageOrange", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconMerc {
            get {
                object obj = ResourceManager.GetObject("skinIconMerc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconMercRed {
            get {
                object obj = ResourceManager.GetObject("skinIconMercRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconRailgunner {
            get {
                object obj = ResourceManager.GetObject("skinIconRailgunner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconToolbot {
            get {
                object obj = ResourceManager.GetObject("skinIconToolbot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconToolbot2 {
            get {
                object obj = ResourceManager.GetObject("skinIconToolbot2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconVoidSurvivor {
            get {
                object obj = ResourceManager.GetObject("skinIconVoidSurvivor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconVoidSurvivorIMP {
            get {
                object obj = ResourceManager.GetObject("skinIconVoidSurvivorIMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedCoatDiffuse {
            get {
                object obj = ResourceManager.GetObject("texBanditRedCoatDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedCoatDiffusePURPLE {
            get {
                object obj = ResourceManager.GetObject("texBanditRedCoatDiffusePURPLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedDiffuse {
            get {
                object obj = ResourceManager.GetObject("texBanditRedDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedDiffusePURPLE {
            get {
                object obj = ResourceManager.GetObject("texBanditRedDiffusePURPLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedEmission {
            get {
                object obj = ResourceManager.GetObject("texBanditRedEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedEmissionPURPLE {
            get {
                object obj = ResourceManager.GetObject("texBanditRedEmissionPURPLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedSkinIcon {
            get {
                object obj = ResourceManager.GetObject("texBanditRedSkinIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedSkinIconPURPLE {
            get {
                object obj = ResourceManager.GetObject("texBanditRedSkinIconPURPLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditShotgunDiffuse {
            get {
                object obj = ResourceManager.GetObject("texBanditShotgunDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditShotgunDiffusePURPLE {
            get {
                object obj = ResourceManager.GetObject("texBanditShotgunDiffusePURPLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCaptainJacketDiffuseRED {
            get {
                object obj = ResourceManager.GetObject("texCaptainJacketDiffuseRED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCaptainPaletteRED2 {
            get {
                object obj = ResourceManager.GetObject("texCaptainPaletteRED2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCaptainPinkSkinIcon {
            get {
                object obj = ResourceManager.GetObject("texCaptainPinkSkinIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texChefDefault {
            get {
                object obj = ResourceManager.GetObject("texChefDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texChefRed {
            get {
                object obj = ResourceManager.GetObject("texChefRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCommandoPaletteDiffuse {
            get {
                object obj = ResourceManager.GetObject("texCommandoPaletteDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoDiffuse {
            get {
                object obj = ResourceManager.GetObject("texCrocoDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoEmission {
            get {
                object obj = ResourceManager.GetObject("texCrocoEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoPoisonMask {
            get {
                object obj = ResourceManager.GetObject("texCrocoPoisonMask", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoSpinesDiffuse {
            get {
                object obj = ResourceManager.GetObject("texCrocoSpinesDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texDifficultyEclipse8Icon {
            get {
                object obj = ResourceManager.GetObject("texDifficultyEclipse8Icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texDroneBody {
            get {
                object obj = ResourceManager.GetObject("texDroneBody", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texDroneBodyEmission {
            get {
                object obj = ResourceManager.GetObject("texDroneBodyEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEngiDiffuseAlt2 {
            get {
                object obj = ResourceManager.GetObject("texEngiDiffuseAlt2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEngiEmissionAlt2 {
            get {
                object obj = ResourceManager.GetObject("texEngiEmissionAlt2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEngiTurretDiffuseAlt2 {
            get {
                object obj = ResourceManager.GetObject("texEngiTurretDiffuseAlt2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHANDSkinIconDefault {
            get {
                object obj = ResourceManager.GetObject("texHANDSkinIconDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHANDSkinIconRorr {
            get {
                object obj = ResourceManager.GetObject("texHANDSkinIconRorr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHuntressDiffuse {
            get {
                object obj = ResourceManager.GetObject("texHuntressDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHuntressDiffuseBow {
            get {
                object obj = ResourceManager.GetObject("texHuntressDiffuseBow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHuntressEmission {
            get {
                object obj = ResourceManager.GetObject("texHuntressEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texItEquipmentBasic {
            get {
                object obj = ResourceManager.GetObject("texItEquipmentBasic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITEquipmentBoss {
            get {
                object obj = ResourceManager.GetObject("texITEquipmentBoss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texItFamilyBasic {
            get {
                object obj = ResourceManager.GetObject("texItFamilyBasic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITHaunted {
            get {
                object obj = ResourceManager.GetObject("texITHaunted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITHauntedBoss {
            get {
                object obj = ResourceManager.GetObject("texITHauntedBoss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITWaveBossIconMountain {
            get {
                object obj = ResourceManager.GetObject("texITWaveBossIconMountain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITWaveDefaultWhite {
            get {
                object obj = ResourceManager.GetObject("texITWaveDefaultWhite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITWaveGupIcon {
            get {
                object obj = ResourceManager.GetObject("texITWaveGupIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITWaveGupIconBasic {
            get {
                object obj = ResourceManager.GetObject("texITWaveGupIconBasic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITWaveJetpack {
            get {
                object obj = ResourceManager.GetObject("texITWaveJetpack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITWaveLunarEliteIcon {
            get {
                object obj = ResourceManager.GetObject("texITWaveLunarEliteIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITWaveLunarHeresy {
            get {
                object obj = ResourceManager.GetObject("texITWaveLunarHeresy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITWaveScavLunarIcon {
            get {
                object obj = ResourceManager.GetObject("texITWaveScavLunarIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITWaveSuperDevestator {
            get {
                object obj = ResourceManager.GetObject("texITWaveSuperDevestator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texITWaveTitanGoldIcon {
            get {
                object obj = ResourceManager.GetObject("texITWaveTitanGoldIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texLoaderPilotDiffuse {
            get {
                object obj = ResourceManager.GetObject("texLoaderPilotDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMageDiffuseAlt {
            get {
                object obj = ResourceManager.GetObject("texMageDiffuseAlt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMageDiffuseORANGE {
            get {
                object obj = ResourceManager.GetObject("texMageDiffuseORANGE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercDiffuse {
            get {
                object obj = ResourceManager.GetObject("texMercDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercDiffuseRed {
            get {
                object obj = ResourceManager.GetObject("texMercDiffuseRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercEmission {
            get {
                object obj = ResourceManager.GetObject("texMercEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercEmissionRED {
            get {
                object obj = ResourceManager.GetObject("texMercEmissionRED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercSwordDiffuse {
            get {
                object obj = ResourceManager.GetObject("texMercSwordDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercSwordDiffuseRed {
            get {
                object obj = ResourceManager.GetObject("texMercSwordDiffuseRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRabbitEarsDiffuse {
            get {
                object obj = ResourceManager.GetObject("texRabbitEarsDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRailgunEmission {
            get {
                object obj = ResourceManager.GetObject("texRailgunEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRailGunnerDiffuse {
            get {
                object obj = ResourceManager.GetObject("texRailGunnerDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampCrocoDiseaseDark {
            get {
                object obj = ResourceManager.GetObject("texRampCrocoDiseaseDark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampEngiAlt2 {
            get {
                object obj = ResourceManager.GetObject("texRampEngiAlt2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampFallbootsRed {
            get {
                object obj = ResourceManager.GetObject("texRampFallbootsRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntress {
            get {
                object obj = ResourceManager.GetObject("texRampHuntress", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressRed {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressSoft {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressSoft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressSoft2 {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressSoft2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampMageFire {
            get {
                object obj = ResourceManager.GetObject("texRampMageFire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampNullifierOffset {
            get {
                object obj = ResourceManager.GetObject("texRampNullifierOffset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampNullifierOffsetIMP {
            get {
                object obj = ResourceManager.GetObject("texRampNullifierOffsetIMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampPulseLunar {
            get {
                object obj = ResourceManager.GetObject("texRampPulseLunar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampPulseNoHeal {
            get {
                object obj = ResourceManager.GetObject("texRampPulseNoHeal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampPulseSuck {
            get {
                object obj = ResourceManager.GetObject("texRampPulseSuck", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampPulseVoid {
            get {
                object obj = ResourceManager.GetObject("texRampPulseVoid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSkinEngi3 {
            get {
                object obj = ResourceManager.GetObject("texSkinEngi3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texToolbotNew {
            get {
                object obj = ResourceManager.GetObject("texToolbotNew", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texToolbotNew2 {
            get {
                object obj = ResourceManager.GetObject("texToolbotNew2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotBlueFlowerDiffuse {
            get {
                object obj = ResourceManager.GetObject("texTreebotBlueFlowerDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotBlueLeafDiffuse {
            get {
                object obj = ResourceManager.GetObject("texTreebotBlueLeafDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotBlueSkinIcon {
            get {
                object obj = ResourceManager.GetObject("texTreebotBlueSkinIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotBlueTreeBarkDiffuse {
            get {
                object obj = ResourceManager.GetObject("texTreebotBlueTreeBarkDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTrimSheetConstructionLoaderAlt1 {
            get {
                object obj = ResourceManager.GetObject("texTrimSheetConstructionLoaderAlt1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTrimSheetMilitaryLightMetal {
            get {
                object obj = ResourceManager.GetObject("texTrimSheetMilitaryLightMetal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTrimSheetRailGunnerMetalBody {
            get {
                object obj = ResourceManager.GetObject("texTrimSheetRailGunnerMetalBody", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texVoidSurvivorFleshDiffuse {
            get {
                object obj = ResourceManager.GetObject("texVoidSurvivorFleshDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texVoidSurvivorFleshDiffuseIMP {
            get {
                object obj = ResourceManager.GetObject("texVoidSurvivorFleshDiffuseIMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texVoidSurvivorFleshEmission {
            get {
                object obj = ResourceManager.GetObject("texVoidSurvivorFleshEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texVoidSurvivorFleshEmissionIMP {
            get {
                object obj = ResourceManager.GetObject("texVoidSurvivorFleshEmissionIMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
